### ISSUE TITLE
avatar image support

### ISSUE THREAD

**Issue by nep-0** [syorito-hatsuki/bluemap-custom-skin-server#8] opened 2024-04-29 02:28 UTC
Would it be feasible to add support for avatar image URLs? Some skin servers don't provide APIs for querying skin texture images by username or UID.

**Comment by syorito-hatsuki** [comment] 2024-04-29 04:33
Technically yes because it fabric, but by BlueMap provided method it impossible. I don't have time currently, so I think I make it as seperated add-on some where at June.

**Comment by syorito-hatsuki** [comment] 2024-05-03 15:27
Average waiting time 1-2 week

**Comment by syorito-hatsuki** [comment] 2024-05-04 21:18
![image](https://github.com/syorito-hatsuki/bluemap-custom-skin-server/assets/33298273/5716db64-37a8-4337-8616-ac7c66766d60)
Got official support from BlueMap author Blue, so I think it gonna be released in few days after some tests and checkout how that part of API works

**Comment by syorito-hatsuki** [comment] 2024-05-04 21:21
If you API is open its can be good for test if you give link for it and few working names / uuids (depend what our API use), because I don't have any server that use this kind of API

**Comment by nep-0** [comment] 2024-05-05 02:00
> If you API is open its can be good for test if you give link for it and few working names / uuids (depend what our API use), because I don't have any server that use this kind of API

Sure. I'm happy to help.
https://littleskin.cn/avatar/player/blueburry23333
https://littleskin.cn/avatar/player/Jeff4F5DA2

https://littleskin.cn/avatar/user/5a2422bf755c43349d81cb374715c8ec
https://littleskin.cn/avatar/user/fbe151a6fa8e446d8249ac963c4c28ec

**Comment by syorito-hatsuki** [comment] 2024-05-05 18:50
> > If you API is open its can be good for test if you give link for it and few working names / uuids (depend what our API use), because I don't have any server that use this kind of API
> 
> Sure. I'm happy to help. https://littleskin.cn/avatar/player/blueburry23333 https://littleskin.cn/avatar/player/Jeff4F5DA2
> 
> https://littleskin.cn/avatar/user/5a2422bf755c43349d81cb374715c8ec https://littleskin.cn/avatar/user/fbe151a6fa8e446d8249ac963c4c28ec

Little bit sad, but global news. Last time when I work with BlueMap it was 3.17 and all works. But in 3.18 we got breaking changes and now mod can't work, so I need first invent any other way for fix that. The problem is global because changes breaks possibility to get Player Name from UUID, so I need do my own way to capture it at moment what I need. And if moment like that not exist... In baddest way I gonna request all to join 2 time for get they skin by name (0 problems with UUID) 🫡

**Comment by syorito-hatsuki** [comment] 2024-05-07 14:18
Its took while, but faster that expected. Should work fine, require copy new config from description or delete old for generate new.

https://modrinth.com/mod/bcss/version/2024.5.1

**Closed as completed by syorito-hatsuki** 2024-05-07 14:18 UTC
Labels: 3rd
